/*
 * generated by Xtext 2.13.0
 */
package ctwedge.ide

import com.google.inject.Guice
import ctwedge.CTWedgeRuntimeModule
import ctwedge.CTWedgeStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class CTWedgeIdeSetup extends CTWedgeStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new CTWedgeRuntimeModule, new CTWedgeIdeModule))
	}
	
}
