/*
 * generated by Xtext 2.22.0
 */
package ctwedge.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import ctwedge.CTWedgeRuntimeModule;
import ctwedge.CTWedgeStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CTWedgeIdeSetup extends CTWedgeStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CTWedgeRuntimeModule(), new CTWedgeIdeModule()));
	}
	
}
