/**
 * generated by Xtext 2.12.0
 */
package ctwedge.ctWedge;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Enumerative</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ctwedge.ctWedge.Enumerative#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see ctwedge.ctWedge.CtWedgePackage#getEnumerative()
 * @model
 * @generated
 */
public interface Enumerative extends Parameter
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link ctwedge.ctWedge.Element}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see ctwedge.ctWedge.CtWedgePackage#getEnumerative_Elements()
   * @model containment="true"
   * @generated
   */
  EList<Element> getElements();

} // Enumerative
