/**
 * generated by Xtext 2.13.0
 */
package ctwedge;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CTWedgeStandaloneSetup /* implements CTWedgeStandaloneSetupGenerated  */{
  public static void doSetup() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method createInjectorAndDoEMFRegistration() is undefined for the type CTWedgeStandaloneSetup");
  }
}
