/**
 * generated by Xtext 2.13.0
 */
package ctwedge;

import ctwedge.CTWedgeStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class CTWedgeStandaloneSetup extends CTWedgeStandaloneSetupGenerated {
  public static void doSetup() {
    new CTWedgeStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
