/**
 * generated by Xtext 2.15.0
 */
package ctwedge.ui;

import ctwedge.ui.AbstractCTWedgeUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class CTWedgeUiModule extends AbstractCTWedgeUiModule {
  public CTWedgeUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
