/**
 * generated by Xtext 2.13.0
 */
package ctwedge.ui.contentassist;

import ctwedge.ui.contentassist.AbstractCTWedgeProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class CTWedgeProposalProvider extends AbstractCTWedgeProposalProvider {
}
