/**
 * generated by Xtext 2.12.0
 */
package ctwedge.ctWedge.impl;

import ctwedge.ctWedge.CtWedgePackage;
import ctwedge.ctWedge.Expression;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ExpressionImpl extends ConstraintImpl implements Expression
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CtWedgePackage.Literals.EXPRESSION;
  }

} //ExpressionImpl
