/**
 * generated by Xtext 2.13.0
 */
package ctwedge.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import ctwedge.CTWedgeRuntimeModule;
import ctwedge.CTWedgeStandaloneSetup;
import ctwedge.ide.CTWedgeIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class CTWedgeIdeSetup extends CTWedgeStandaloneSetup {
  public Injector createInjector() {
    CTWedgeRuntimeModule _cTWedgeRuntimeModule = new CTWedgeRuntimeModule();
    CTWedgeIdeModule _cTWedgeIdeModule = new CTWedgeIdeModule();
    return Guice.createInjector(Modules2.mixin(_cTWedgeRuntimeModule, _cTWedgeIdeModule));
  }
}
