/**
 * generated by Xtext 2.13.0
 */
package ctwedge.ide;

import ctwedge.CTWedgeStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CTWedgeIdeSetup extends CTWedgeStandaloneSetup {
  public Object createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\ncreateInjector cannot be resolved"
      + "\nmixin cannot be resolved");
  }
}
