/**
 * generated by Xtext 2.13.0
 */
package ctwedge.ide;

import ctwedge.ide.AbstractCTWedgeIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class CTWedgeIdeModule extends AbstractCTWedgeIdeModule {
}
