/*
 * generated by Xtext 2.13.0
 */
package ctwedge.parser.antlr;

import com.google.inject.Inject;
import ctwedge.parser.antlr.internal.InternalCTWedgeParser;
import ctwedge.services.CTWedgeGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class CTWedgeParser extends AbstractAntlrParser {

	@Inject
	private CTWedgeGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCTWedgeParser createParser(XtextTokenStream stream) {
		return new InternalCTWedgeParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "CitModel";
	}

	public CTWedgeGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CTWedgeGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
