/**
 * generated by Xtext 2.13.0
 */
package ctwedge.validation;

import ctwedge.validation.AbstractCTWedgeValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class CTWedgeValidator extends AbstractCTWedgeValidator {
}
