/**
 * generated by Xtext 2.13.0
 */
package ctwedge.web;

import com.google.inject.Injector;
import ctwedge.CTWedgeStandaloneSetup;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@SuppressWarnings("all")
public class CTWedgeWebSetup extends CTWedgeStandaloneSetup {
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from CTWedgeRuntimeModule to Module"
      + "\nType mismatch: cannot convert from CTWedgeIdeModule to Module");
  }
}
