/**
 * generated by Xtext 2.13.0
 */
package ctwedge.web;

import ctwedge.web.AbstractCTWedgeWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class CTWedgeWebModule extends AbstractCTWedgeWebModule {
}
