/**
 * generated by Xtext 2.13.0
 */
package ctwedge.web;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@SuppressWarnings("all")
public class CTWedgeWebSetup /* implements CTWedgeStandaloneSetup  */{
  @Override
  public /* Injector */Object createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field Guice is undefined"
      + "\nThe method or field Modules2 is undefined"
      + "\nCTWedgeRuntimeModule cannot be resolved."
      + "\nCTWedgeIdeModule cannot be resolved."
      + "\ncreateInjector cannot be resolved"
      + "\nmixin cannot be resolved");
  }
}
