/**
 * generated by Xtext 2.13.0
 */
package ctwedge.web;

/**
 * This program starts an HTTP server for testing the web integration of your DSL.
 * Just execute it and point a web browser to http://localhost:8080/
 */
@SuppressWarnings("all")
public class ServerLauncher {
  public static void main(final String[] args) {
    throw new Error("Unresolved compilation problems:"
      + "\nServer cannot be resolved."
      + "\nWebAppContext cannot be resolved."
      + "\nThe method resourceBase(String) is undefined"
      + "\nThe method welcomeFiles(List<String>) is undefined"
      + "\nThe method contextPath(String) is undefined"
      + "\nThe method configurations(List<Object>) is undefined"
      + "\nAnnotationConfiguration cannot be resolved."
      + "\nWebXmlConfiguration cannot be resolved."
      + "\nWebInfConfiguration cannot be resolved."
      + "\nMetaInfConfiguration cannot be resolved."
      + "\nThe method setAttribute(Object, String) is undefined"
      + "\nThe method or field WebInfConfiguration is undefined"
      + "\nThe method setInitParameter(String, String) is undefined"
      + "\nSlf4jLog cannot be resolved."
      + "\n+ cannot be resolved."
      + "\n!= cannot be resolved."
      + "\n- cannot be resolved."
      + "\nhandler cannot be resolved"
      + "\n=> cannot be resolved"
      + "\nCONTAINER_JAR_PATTERN cannot be resolved"
      + "\nstart cannot be resolved"
      + "\ninfo cannot be resolved"
      + "\ngetURI cannot be resolved"
      + "\n+ cannot be resolved"
      + "\ninfo cannot be resolved"
      + "\nstop cannot be resolved"
      + "\nwarn cannot be resolved"
      + "\njoin cannot be resolved"
      + "\nwarn cannot be resolved");
  }
}
