/**
 * generated by Xtext 2.15.0
 */
package ctwedge.ctWedge;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bool</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ctwedge.ctWedge.CtWedgePackage#getBool()
 * @model
 * @generated
 */
public interface Bool extends Parameter
{
} // Bool
