/**
 * generated by Xtext 2.14.0
 */
package ctwedge.ctWedge;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constraint</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ctwedge.ctWedge.CtWedgePackage#getConstraint()
 * @model
 * @generated
 */
public interface Constraint extends EObject
{
} // Constraint
