/**
 * generated by Xtext 2.14.0
 */
package ctwedge.ctWedge;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see ctwedge.ctWedge.CtWedgeFactory
 * @model kind="package"
 * @generated
 */
public interface CtWedgePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "ctWedge";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.CtWedge.ctwedge";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "ctWedge";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CtWedgePackage eINSTANCE = ctwedge.ctWedge.impl.CtWedgePackageImpl.init();

  /**
   * The meta object id for the '{@link ctwedge.ctWedge.impl.CitModelImpl <em>Cit Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ctwedge.ctWedge.impl.CitModelImpl
   * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getCitModel()
   * @generated
   */
  int CIT_MODEL = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CIT_MODEL__NAME = 0;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CIT_MODEL__PARAMETERS = 1;

  /**
   * The feature id for the '<em><b>Constraints</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CIT_MODEL__CONSTRAINTS = 2;

  /**
   * The number of structural features of the '<em>Cit Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CIT_MODEL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link ctwedge.ctWedge.impl.ParameterImpl <em>Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ctwedge.ctWedge.impl.ParameterImpl
   * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getParameter()
   * @generated
   */
  int PARAMETER = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__NAME = 0;

  /**
   * The number of structural features of the '<em>Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ctwedge.ctWedge.impl.BoolImpl <em>Bool</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ctwedge.ctWedge.impl.BoolImpl
   * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getBool()
   * @generated
   */
  int BOOL = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL__NAME = PARAMETER__NAME;

  /**
   * The number of structural features of the '<em>Bool</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_FEATURE_COUNT = PARAMETER_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ctwedge.ctWedge.impl.EnumerativeImpl <em>Enumerative</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ctwedge.ctWedge.impl.EnumerativeImpl
   * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getEnumerative()
   * @generated
   */
  int ENUMERATIVE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUMERATIVE__NAME = PARAMETER__NAME;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUMERATIVE__ELEMENTS = PARAMETER_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Enumerative</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUMERATIVE_FEATURE_COUNT = PARAMETER_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ctwedge.ctWedge.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ctwedge.ctWedge.impl.ElementImpl
   * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ctwedge.ctWedge.impl.RangeImpl <em>Range</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ctwedge.ctWedge.impl.RangeImpl
   * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getRange()
   * @generated
   */
  int RANGE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE__NAME = PARAMETER__NAME;

  /**
   * The feature id for the '<em><b>Begin</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE__BEGIN = PARAMETER_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>End</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE__END = PARAMETER_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Step</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE__STEP = PARAMETER_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Range</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE_FEATURE_COUNT = PARAMETER_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link ctwedge.ctWedge.impl.ConstraintImpl <em>Constraint</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ctwedge.ctWedge.impl.ConstraintImpl
   * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getConstraint()
   * @generated
   */
  int CONSTRAINT = 6;

  /**
   * The number of structural features of the '<em>Constraint</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link ctwedge.ctWedge.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ctwedge.ctWedge.impl.ExpressionImpl
   * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 7;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = CONSTRAINT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ctwedge.ctWedge.impl.AtomicPredicateImpl <em>Atomic Predicate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ctwedge.ctWedge.impl.AtomicPredicateImpl
   * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getAtomicPredicate()
   * @generated
   */
  int ATOMIC_PREDICATE = 8;

  /**
   * The feature id for the '<em><b>Bool Const</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOMIC_PREDICATE__BOOL_CONST = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOMIC_PREDICATE__NAME = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Atomic Predicate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOMIC_PREDICATE_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link ctwedge.ctWedge.impl.ImpliesExpressionImpl <em>Implies Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ctwedge.ctWedge.impl.ImpliesExpressionImpl
   * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getImpliesExpression()
   * @generated
   */
  int IMPLIES_EXPRESSION = 9;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPLIES_EXPRESSION__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPLIES_EXPRESSION__OP = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPLIES_EXPRESSION__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Implies Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPLIES_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link ctwedge.ctWedge.impl.OrExpressionImpl <em>Or Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ctwedge.ctWedge.impl.OrExpressionImpl
   * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getOrExpression()
   * @generated
   */
  int OR_EXPRESSION = 10;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_EXPRESSION__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_EXPRESSION__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Or Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link ctwedge.ctWedge.impl.AndExpressionImpl <em>And Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ctwedge.ctWedge.impl.AndExpressionImpl
   * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getAndExpression()
   * @generated
   */
  int AND_EXPRESSION = 11;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_EXPRESSION__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_EXPRESSION__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>And Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link ctwedge.ctWedge.impl.EqualExpressionImpl <em>Equal Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ctwedge.ctWedge.impl.EqualExpressionImpl
   * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getEqualExpression()
   * @generated
   */
  int EQUAL_EXPRESSION = 12;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUAL_EXPRESSION__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUAL_EXPRESSION__OP = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUAL_EXPRESSION__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Equal Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUAL_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link ctwedge.ctWedge.impl.RelationalExpressionImpl <em>Relational Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ctwedge.ctWedge.impl.RelationalExpressionImpl
   * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getRelationalExpression()
   * @generated
   */
  int RELATIONAL_EXPRESSION = 13;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONAL_EXPRESSION__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONAL_EXPRESSION__OP = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONAL_EXPRESSION__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Relational Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONAL_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link ctwedge.ctWedge.impl.PlusMinusImpl <em>Plus Minus</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ctwedge.ctWedge.impl.PlusMinusImpl
   * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getPlusMinus()
   * @generated
   */
  int PLUS_MINUS = 14;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS_MINUS__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS_MINUS__OP = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS_MINUS__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Plus Minus</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS_MINUS_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link ctwedge.ctWedge.impl.ModMultDivImpl <em>Mod Mult Div</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ctwedge.ctWedge.impl.ModMultDivImpl
   * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getModMultDiv()
   * @generated
   */
  int MOD_MULT_DIV = 15;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOD_MULT_DIV__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOD_MULT_DIV__OP = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOD_MULT_DIV__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Mod Mult Div</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOD_MULT_DIV_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link ctwedge.ctWedge.impl.NotExpressionImpl <em>Not Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ctwedge.ctWedge.impl.NotExpressionImpl
   * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getNotExpression()
   * @generated
   */
  int NOT_EXPRESSION = 16;

  /**
   * The feature id for the '<em><b>Predicate</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT_EXPRESSION__PREDICATE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Not Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ctwedge.ctWedge.Operators <em>Operators</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ctwedge.ctWedge.Operators
   * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getOperators()
   * @generated
   */
  int OPERATORS = 17;

  /**
   * The meta object id for the '{@link ctwedge.ctWedge.PlusMinusOperators <em>Plus Minus Operators</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ctwedge.ctWedge.PlusMinusOperators
   * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getPlusMinusOperators()
   * @generated
   */
  int PLUS_MINUS_OPERATORS = 18;

  /**
   * The meta object id for the '{@link ctwedge.ctWedge.ModMultDivOperators <em>Mod Mult Div Operators</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ctwedge.ctWedge.ModMultDivOperators
   * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getModMultDivOperators()
   * @generated
   */
  int MOD_MULT_DIV_OPERATORS = 19;

  /**
   * The meta object id for the '{@link ctwedge.ctWedge.ImpliesOperator <em>Implies Operator</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ctwedge.ctWedge.ImpliesOperator
   * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getImpliesOperator()
   * @generated
   */
  int IMPLIES_OPERATOR = 20;


  /**
   * Returns the meta object for class '{@link ctwedge.ctWedge.CitModel <em>Cit Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cit Model</em>'.
   * @see ctwedge.ctWedge.CitModel
   * @generated
   */
  EClass getCitModel();

  /**
   * Returns the meta object for the attribute '{@link ctwedge.ctWedge.CitModel#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ctwedge.ctWedge.CitModel#getName()
   * @see #getCitModel()
   * @generated
   */
  EAttribute getCitModel_Name();

  /**
   * Returns the meta object for the containment reference list '{@link ctwedge.ctWedge.CitModel#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parameters</em>'.
   * @see ctwedge.ctWedge.CitModel#getParameters()
   * @see #getCitModel()
   * @generated
   */
  EReference getCitModel_Parameters();

  /**
   * Returns the meta object for the containment reference list '{@link ctwedge.ctWedge.CitModel#getConstraints <em>Constraints</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Constraints</em>'.
   * @see ctwedge.ctWedge.CitModel#getConstraints()
   * @see #getCitModel()
   * @generated
   */
  EReference getCitModel_Constraints();

  /**
   * Returns the meta object for class '{@link ctwedge.ctWedge.Parameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter</em>'.
   * @see ctwedge.ctWedge.Parameter
   * @generated
   */
  EClass getParameter();

  /**
   * Returns the meta object for the attribute '{@link ctwedge.ctWedge.Parameter#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ctwedge.ctWedge.Parameter#getName()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_Name();

  /**
   * Returns the meta object for class '{@link ctwedge.ctWedge.Bool <em>Bool</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bool</em>'.
   * @see ctwedge.ctWedge.Bool
   * @generated
   */
  EClass getBool();

  /**
   * Returns the meta object for class '{@link ctwedge.ctWedge.Enumerative <em>Enumerative</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Enumerative</em>'.
   * @see ctwedge.ctWedge.Enumerative
   * @generated
   */
  EClass getEnumerative();

  /**
   * Returns the meta object for the containment reference list '{@link ctwedge.ctWedge.Enumerative#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see ctwedge.ctWedge.Enumerative#getElements()
   * @see #getEnumerative()
   * @generated
   */
  EReference getEnumerative_Elements();

  /**
   * Returns the meta object for class '{@link ctwedge.ctWedge.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see ctwedge.ctWedge.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for the attribute '{@link ctwedge.ctWedge.Element#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ctwedge.ctWedge.Element#getName()
   * @see #getElement()
   * @generated
   */
  EAttribute getElement_Name();

  /**
   * Returns the meta object for class '{@link ctwedge.ctWedge.Range <em>Range</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Range</em>'.
   * @see ctwedge.ctWedge.Range
   * @generated
   */
  EClass getRange();

  /**
   * Returns the meta object for the attribute '{@link ctwedge.ctWedge.Range#getBegin <em>Begin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Begin</em>'.
   * @see ctwedge.ctWedge.Range#getBegin()
   * @see #getRange()
   * @generated
   */
  EAttribute getRange_Begin();

  /**
   * Returns the meta object for the attribute '{@link ctwedge.ctWedge.Range#getEnd <em>End</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>End</em>'.
   * @see ctwedge.ctWedge.Range#getEnd()
   * @see #getRange()
   * @generated
   */
  EAttribute getRange_End();

  /**
   * Returns the meta object for the attribute '{@link ctwedge.ctWedge.Range#getStep <em>Step</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Step</em>'.
   * @see ctwedge.ctWedge.Range#getStep()
   * @see #getRange()
   * @generated
   */
  EAttribute getRange_Step();

  /**
   * Returns the meta object for class '{@link ctwedge.ctWedge.Constraint <em>Constraint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constraint</em>'.
   * @see ctwedge.ctWedge.Constraint
   * @generated
   */
  EClass getConstraint();

  /**
   * Returns the meta object for class '{@link ctwedge.ctWedge.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see ctwedge.ctWedge.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link ctwedge.ctWedge.AtomicPredicate <em>Atomic Predicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Atomic Predicate</em>'.
   * @see ctwedge.ctWedge.AtomicPredicate
   * @generated
   */
  EClass getAtomicPredicate();

  /**
   * Returns the meta object for the attribute '{@link ctwedge.ctWedge.AtomicPredicate#getBoolConst <em>Bool Const</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Bool Const</em>'.
   * @see ctwedge.ctWedge.AtomicPredicate#getBoolConst()
   * @see #getAtomicPredicate()
   * @generated
   */
  EAttribute getAtomicPredicate_BoolConst();

  /**
   * Returns the meta object for the attribute '{@link ctwedge.ctWedge.AtomicPredicate#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ctwedge.ctWedge.AtomicPredicate#getName()
   * @see #getAtomicPredicate()
   * @generated
   */
  EAttribute getAtomicPredicate_Name();

  /**
   * Returns the meta object for class '{@link ctwedge.ctWedge.ImpliesExpression <em>Implies Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Implies Expression</em>'.
   * @see ctwedge.ctWedge.ImpliesExpression
   * @generated
   */
  EClass getImpliesExpression();

  /**
   * Returns the meta object for the containment reference '{@link ctwedge.ctWedge.ImpliesExpression#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see ctwedge.ctWedge.ImpliesExpression#getLeft()
   * @see #getImpliesExpression()
   * @generated
   */
  EReference getImpliesExpression_Left();

  /**
   * Returns the meta object for the attribute '{@link ctwedge.ctWedge.ImpliesExpression#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see ctwedge.ctWedge.ImpliesExpression#getOp()
   * @see #getImpliesExpression()
   * @generated
   */
  EAttribute getImpliesExpression_Op();

  /**
   * Returns the meta object for the containment reference '{@link ctwedge.ctWedge.ImpliesExpression#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see ctwedge.ctWedge.ImpliesExpression#getRight()
   * @see #getImpliesExpression()
   * @generated
   */
  EReference getImpliesExpression_Right();

  /**
   * Returns the meta object for class '{@link ctwedge.ctWedge.OrExpression <em>Or Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Or Expression</em>'.
   * @see ctwedge.ctWedge.OrExpression
   * @generated
   */
  EClass getOrExpression();

  /**
   * Returns the meta object for the containment reference '{@link ctwedge.ctWedge.OrExpression#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see ctwedge.ctWedge.OrExpression#getLeft()
   * @see #getOrExpression()
   * @generated
   */
  EReference getOrExpression_Left();

  /**
   * Returns the meta object for the containment reference '{@link ctwedge.ctWedge.OrExpression#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see ctwedge.ctWedge.OrExpression#getRight()
   * @see #getOrExpression()
   * @generated
   */
  EReference getOrExpression_Right();

  /**
   * Returns the meta object for class '{@link ctwedge.ctWedge.AndExpression <em>And Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>And Expression</em>'.
   * @see ctwedge.ctWedge.AndExpression
   * @generated
   */
  EClass getAndExpression();

  /**
   * Returns the meta object for the containment reference '{@link ctwedge.ctWedge.AndExpression#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see ctwedge.ctWedge.AndExpression#getLeft()
   * @see #getAndExpression()
   * @generated
   */
  EReference getAndExpression_Left();

  /**
   * Returns the meta object for the containment reference '{@link ctwedge.ctWedge.AndExpression#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see ctwedge.ctWedge.AndExpression#getRight()
   * @see #getAndExpression()
   * @generated
   */
  EReference getAndExpression_Right();

  /**
   * Returns the meta object for class '{@link ctwedge.ctWedge.EqualExpression <em>Equal Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Equal Expression</em>'.
   * @see ctwedge.ctWedge.EqualExpression
   * @generated
   */
  EClass getEqualExpression();

  /**
   * Returns the meta object for the containment reference '{@link ctwedge.ctWedge.EqualExpression#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see ctwedge.ctWedge.EqualExpression#getLeft()
   * @see #getEqualExpression()
   * @generated
   */
  EReference getEqualExpression_Left();

  /**
   * Returns the meta object for the attribute '{@link ctwedge.ctWedge.EqualExpression#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see ctwedge.ctWedge.EqualExpression#getOp()
   * @see #getEqualExpression()
   * @generated
   */
  EAttribute getEqualExpression_Op();

  /**
   * Returns the meta object for the containment reference '{@link ctwedge.ctWedge.EqualExpression#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see ctwedge.ctWedge.EqualExpression#getRight()
   * @see #getEqualExpression()
   * @generated
   */
  EReference getEqualExpression_Right();

  /**
   * Returns the meta object for class '{@link ctwedge.ctWedge.RelationalExpression <em>Relational Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Relational Expression</em>'.
   * @see ctwedge.ctWedge.RelationalExpression
   * @generated
   */
  EClass getRelationalExpression();

  /**
   * Returns the meta object for the containment reference '{@link ctwedge.ctWedge.RelationalExpression#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see ctwedge.ctWedge.RelationalExpression#getLeft()
   * @see #getRelationalExpression()
   * @generated
   */
  EReference getRelationalExpression_Left();

  /**
   * Returns the meta object for the attribute '{@link ctwedge.ctWedge.RelationalExpression#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see ctwedge.ctWedge.RelationalExpression#getOp()
   * @see #getRelationalExpression()
   * @generated
   */
  EAttribute getRelationalExpression_Op();

  /**
   * Returns the meta object for the containment reference '{@link ctwedge.ctWedge.RelationalExpression#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see ctwedge.ctWedge.RelationalExpression#getRight()
   * @see #getRelationalExpression()
   * @generated
   */
  EReference getRelationalExpression_Right();

  /**
   * Returns the meta object for class '{@link ctwedge.ctWedge.PlusMinus <em>Plus Minus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Plus Minus</em>'.
   * @see ctwedge.ctWedge.PlusMinus
   * @generated
   */
  EClass getPlusMinus();

  /**
   * Returns the meta object for the containment reference '{@link ctwedge.ctWedge.PlusMinus#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see ctwedge.ctWedge.PlusMinus#getLeft()
   * @see #getPlusMinus()
   * @generated
   */
  EReference getPlusMinus_Left();

  /**
   * Returns the meta object for the attribute '{@link ctwedge.ctWedge.PlusMinus#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see ctwedge.ctWedge.PlusMinus#getOp()
   * @see #getPlusMinus()
   * @generated
   */
  EAttribute getPlusMinus_Op();

  /**
   * Returns the meta object for the containment reference '{@link ctwedge.ctWedge.PlusMinus#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see ctwedge.ctWedge.PlusMinus#getRight()
   * @see #getPlusMinus()
   * @generated
   */
  EReference getPlusMinus_Right();

  /**
   * Returns the meta object for class '{@link ctwedge.ctWedge.ModMultDiv <em>Mod Mult Div</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mod Mult Div</em>'.
   * @see ctwedge.ctWedge.ModMultDiv
   * @generated
   */
  EClass getModMultDiv();

  /**
   * Returns the meta object for the containment reference '{@link ctwedge.ctWedge.ModMultDiv#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see ctwedge.ctWedge.ModMultDiv#getLeft()
   * @see #getModMultDiv()
   * @generated
   */
  EReference getModMultDiv_Left();

  /**
   * Returns the meta object for the attribute '{@link ctwedge.ctWedge.ModMultDiv#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see ctwedge.ctWedge.ModMultDiv#getOp()
   * @see #getModMultDiv()
   * @generated
   */
  EAttribute getModMultDiv_Op();

  /**
   * Returns the meta object for the containment reference '{@link ctwedge.ctWedge.ModMultDiv#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see ctwedge.ctWedge.ModMultDiv#getRight()
   * @see #getModMultDiv()
   * @generated
   */
  EReference getModMultDiv_Right();

  /**
   * Returns the meta object for class '{@link ctwedge.ctWedge.NotExpression <em>Not Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Not Expression</em>'.
   * @see ctwedge.ctWedge.NotExpression
   * @generated
   */
  EClass getNotExpression();

  /**
   * Returns the meta object for the containment reference '{@link ctwedge.ctWedge.NotExpression#getPredicate <em>Predicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Predicate</em>'.
   * @see ctwedge.ctWedge.NotExpression#getPredicate()
   * @see #getNotExpression()
   * @generated
   */
  EReference getNotExpression_Predicate();

  /**
   * Returns the meta object for enum '{@link ctwedge.ctWedge.Operators <em>Operators</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Operators</em>'.
   * @see ctwedge.ctWedge.Operators
   * @generated
   */
  EEnum getOperators();

  /**
   * Returns the meta object for enum '{@link ctwedge.ctWedge.PlusMinusOperators <em>Plus Minus Operators</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Plus Minus Operators</em>'.
   * @see ctwedge.ctWedge.PlusMinusOperators
   * @generated
   */
  EEnum getPlusMinusOperators();

  /**
   * Returns the meta object for enum '{@link ctwedge.ctWedge.ModMultDivOperators <em>Mod Mult Div Operators</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Mod Mult Div Operators</em>'.
   * @see ctwedge.ctWedge.ModMultDivOperators
   * @generated
   */
  EEnum getModMultDivOperators();

  /**
   * Returns the meta object for enum '{@link ctwedge.ctWedge.ImpliesOperator <em>Implies Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Implies Operator</em>'.
   * @see ctwedge.ctWedge.ImpliesOperator
   * @generated
   */
  EEnum getImpliesOperator();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  CtWedgeFactory getCtWedgeFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link ctwedge.ctWedge.impl.CitModelImpl <em>Cit Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ctwedge.ctWedge.impl.CitModelImpl
     * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getCitModel()
     * @generated
     */
    EClass CIT_MODEL = eINSTANCE.getCitModel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CIT_MODEL__NAME = eINSTANCE.getCitModel_Name();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CIT_MODEL__PARAMETERS = eINSTANCE.getCitModel_Parameters();

    /**
     * The meta object literal for the '<em><b>Constraints</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CIT_MODEL__CONSTRAINTS = eINSTANCE.getCitModel_Constraints();

    /**
     * The meta object literal for the '{@link ctwedge.ctWedge.impl.ParameterImpl <em>Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ctwedge.ctWedge.impl.ParameterImpl
     * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getParameter()
     * @generated
     */
    EClass PARAMETER = eINSTANCE.getParameter();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__NAME = eINSTANCE.getParameter_Name();

    /**
     * The meta object literal for the '{@link ctwedge.ctWedge.impl.BoolImpl <em>Bool</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ctwedge.ctWedge.impl.BoolImpl
     * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getBool()
     * @generated
     */
    EClass BOOL = eINSTANCE.getBool();

    /**
     * The meta object literal for the '{@link ctwedge.ctWedge.impl.EnumerativeImpl <em>Enumerative</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ctwedge.ctWedge.impl.EnumerativeImpl
     * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getEnumerative()
     * @generated
     */
    EClass ENUMERATIVE = eINSTANCE.getEnumerative();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENUMERATIVE__ELEMENTS = eINSTANCE.getEnumerative_Elements();

    /**
     * The meta object literal for the '{@link ctwedge.ctWedge.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ctwedge.ctWedge.impl.ElementImpl
     * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT__NAME = eINSTANCE.getElement_Name();

    /**
     * The meta object literal for the '{@link ctwedge.ctWedge.impl.RangeImpl <em>Range</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ctwedge.ctWedge.impl.RangeImpl
     * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getRange()
     * @generated
     */
    EClass RANGE = eINSTANCE.getRange();

    /**
     * The meta object literal for the '<em><b>Begin</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RANGE__BEGIN = eINSTANCE.getRange_Begin();

    /**
     * The meta object literal for the '<em><b>End</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RANGE__END = eINSTANCE.getRange_End();

    /**
     * The meta object literal for the '<em><b>Step</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RANGE__STEP = eINSTANCE.getRange_Step();

    /**
     * The meta object literal for the '{@link ctwedge.ctWedge.impl.ConstraintImpl <em>Constraint</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ctwedge.ctWedge.impl.ConstraintImpl
     * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getConstraint()
     * @generated
     */
    EClass CONSTRAINT = eINSTANCE.getConstraint();

    /**
     * The meta object literal for the '{@link ctwedge.ctWedge.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ctwedge.ctWedge.impl.ExpressionImpl
     * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link ctwedge.ctWedge.impl.AtomicPredicateImpl <em>Atomic Predicate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ctwedge.ctWedge.impl.AtomicPredicateImpl
     * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getAtomicPredicate()
     * @generated
     */
    EClass ATOMIC_PREDICATE = eINSTANCE.getAtomicPredicate();

    /**
     * The meta object literal for the '<em><b>Bool Const</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATOMIC_PREDICATE__BOOL_CONST = eINSTANCE.getAtomicPredicate_BoolConst();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATOMIC_PREDICATE__NAME = eINSTANCE.getAtomicPredicate_Name();

    /**
     * The meta object literal for the '{@link ctwedge.ctWedge.impl.ImpliesExpressionImpl <em>Implies Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ctwedge.ctWedge.impl.ImpliesExpressionImpl
     * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getImpliesExpression()
     * @generated
     */
    EClass IMPLIES_EXPRESSION = eINSTANCE.getImpliesExpression();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMPLIES_EXPRESSION__LEFT = eINSTANCE.getImpliesExpression_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMPLIES_EXPRESSION__OP = eINSTANCE.getImpliesExpression_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMPLIES_EXPRESSION__RIGHT = eINSTANCE.getImpliesExpression_Right();

    /**
     * The meta object literal for the '{@link ctwedge.ctWedge.impl.OrExpressionImpl <em>Or Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ctwedge.ctWedge.impl.OrExpressionImpl
     * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getOrExpression()
     * @generated
     */
    EClass OR_EXPRESSION = eINSTANCE.getOrExpression();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR_EXPRESSION__LEFT = eINSTANCE.getOrExpression_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR_EXPRESSION__RIGHT = eINSTANCE.getOrExpression_Right();

    /**
     * The meta object literal for the '{@link ctwedge.ctWedge.impl.AndExpressionImpl <em>And Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ctwedge.ctWedge.impl.AndExpressionImpl
     * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getAndExpression()
     * @generated
     */
    EClass AND_EXPRESSION = eINSTANCE.getAndExpression();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND_EXPRESSION__LEFT = eINSTANCE.getAndExpression_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND_EXPRESSION__RIGHT = eINSTANCE.getAndExpression_Right();

    /**
     * The meta object literal for the '{@link ctwedge.ctWedge.impl.EqualExpressionImpl <em>Equal Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ctwedge.ctWedge.impl.EqualExpressionImpl
     * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getEqualExpression()
     * @generated
     */
    EClass EQUAL_EXPRESSION = eINSTANCE.getEqualExpression();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EQUAL_EXPRESSION__LEFT = eINSTANCE.getEqualExpression_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EQUAL_EXPRESSION__OP = eINSTANCE.getEqualExpression_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EQUAL_EXPRESSION__RIGHT = eINSTANCE.getEqualExpression_Right();

    /**
     * The meta object literal for the '{@link ctwedge.ctWedge.impl.RelationalExpressionImpl <em>Relational Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ctwedge.ctWedge.impl.RelationalExpressionImpl
     * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getRelationalExpression()
     * @generated
     */
    EClass RELATIONAL_EXPRESSION = eINSTANCE.getRelationalExpression();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATIONAL_EXPRESSION__LEFT = eINSTANCE.getRelationalExpression_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RELATIONAL_EXPRESSION__OP = eINSTANCE.getRelationalExpression_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATIONAL_EXPRESSION__RIGHT = eINSTANCE.getRelationalExpression_Right();

    /**
     * The meta object literal for the '{@link ctwedge.ctWedge.impl.PlusMinusImpl <em>Plus Minus</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ctwedge.ctWedge.impl.PlusMinusImpl
     * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getPlusMinus()
     * @generated
     */
    EClass PLUS_MINUS = eINSTANCE.getPlusMinus();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLUS_MINUS__LEFT = eINSTANCE.getPlusMinus_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PLUS_MINUS__OP = eINSTANCE.getPlusMinus_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLUS_MINUS__RIGHT = eINSTANCE.getPlusMinus_Right();

    /**
     * The meta object literal for the '{@link ctwedge.ctWedge.impl.ModMultDivImpl <em>Mod Mult Div</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ctwedge.ctWedge.impl.ModMultDivImpl
     * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getModMultDiv()
     * @generated
     */
    EClass MOD_MULT_DIV = eINSTANCE.getModMultDiv();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MOD_MULT_DIV__LEFT = eINSTANCE.getModMultDiv_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOD_MULT_DIV__OP = eINSTANCE.getModMultDiv_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MOD_MULT_DIV__RIGHT = eINSTANCE.getModMultDiv_Right();

    /**
     * The meta object literal for the '{@link ctwedge.ctWedge.impl.NotExpressionImpl <em>Not Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ctwedge.ctWedge.impl.NotExpressionImpl
     * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getNotExpression()
     * @generated
     */
    EClass NOT_EXPRESSION = eINSTANCE.getNotExpression();

    /**
     * The meta object literal for the '<em><b>Predicate</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NOT_EXPRESSION__PREDICATE = eINSTANCE.getNotExpression_Predicate();

    /**
     * The meta object literal for the '{@link ctwedge.ctWedge.Operators <em>Operators</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ctwedge.ctWedge.Operators
     * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getOperators()
     * @generated
     */
    EEnum OPERATORS = eINSTANCE.getOperators();

    /**
     * The meta object literal for the '{@link ctwedge.ctWedge.PlusMinusOperators <em>Plus Minus Operators</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ctwedge.ctWedge.PlusMinusOperators
     * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getPlusMinusOperators()
     * @generated
     */
    EEnum PLUS_MINUS_OPERATORS = eINSTANCE.getPlusMinusOperators();

    /**
     * The meta object literal for the '{@link ctwedge.ctWedge.ModMultDivOperators <em>Mod Mult Div Operators</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ctwedge.ctWedge.ModMultDivOperators
     * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getModMultDivOperators()
     * @generated
     */
    EEnum MOD_MULT_DIV_OPERATORS = eINSTANCE.getModMultDivOperators();

    /**
     * The meta object literal for the '{@link ctwedge.ctWedge.ImpliesOperator <em>Implies Operator</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ctwedge.ctWedge.ImpliesOperator
     * @see ctwedge.ctWedge.impl.CtWedgePackageImpl#getImpliesOperator()
     * @generated
     */
    EEnum IMPLIES_OPERATOR = eINSTANCE.getImpliesOperator();

  }

} //CtWedgePackage
