/**
 * generated by Xtext 2.13.0
 */
package ctwedge.ctWedge;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ctwedge.ctWedge.CtWedgePackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends Constraint
{
} // Expression
