/**
 * generated by Xtext 2.14.0
 */
package ctwedge.ctWedge;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Range</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ctwedge.ctWedge.Range#getBegin <em>Begin</em>}</li>
 *   <li>{@link ctwedge.ctWedge.Range#getEnd <em>End</em>}</li>
 *   <li>{@link ctwedge.ctWedge.Range#getStep <em>Step</em>}</li>
 * </ul>
 *
 * @see ctwedge.ctWedge.CtWedgePackage#getRange()
 * @model
 * @generated
 */
public interface Range extends Parameter
{
  /**
   * Returns the value of the '<em><b>Begin</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Begin</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Begin</em>' attribute.
   * @see #setBegin(Integer)
   * @see ctwedge.ctWedge.CtWedgePackage#getRange_Begin()
   * @model
   * @generated
   */
  Integer getBegin();

  /**
   * Sets the value of the '{@link ctwedge.ctWedge.Range#getBegin <em>Begin</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Begin</em>' attribute.
   * @see #getBegin()
   * @generated
   */
  void setBegin(Integer value);

  /**
   * Returns the value of the '<em><b>End</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>End</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>End</em>' attribute.
   * @see #setEnd(Integer)
   * @see ctwedge.ctWedge.CtWedgePackage#getRange_End()
   * @model
   * @generated
   */
  Integer getEnd();

  /**
   * Sets the value of the '{@link ctwedge.ctWedge.Range#getEnd <em>End</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End</em>' attribute.
   * @see #getEnd()
   * @generated
   */
  void setEnd(Integer value);

  /**
   * Returns the value of the '<em><b>Step</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Step</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Step</em>' attribute.
   * @see #setStep(int)
   * @see ctwedge.ctWedge.CtWedgePackage#getRange_Step()
   * @model
   * @generated
   */
  int getStep();

  /**
   * Sets the value of the '{@link ctwedge.ctWedge.Range#getStep <em>Step</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Step</em>' attribute.
   * @see #getStep()
   * @generated
   */
  void setStep(int value);

} // Range
