/*
 * generated by Xtext 2.12.0
 */
package ctwedge.ide.contentassist.antlr;

import com.google.inject.Inject;
import ctwedge.ide.contentassist.antlr.internal.InternalCTWedgeParser;
import ctwedge.services.CTWedgeGrammarAccess;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class CTWedgeParser extends AbstractContentAssistParser {

	@Inject
	private CTWedgeGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalCTWedgeParser createParser() {
		InternalCTWedgeParser result = new InternalCTWedgeParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getParameterAccess().getAlternatives_0(), "rule__Parameter__Alternatives_0");
					put(grammarAccess.getPrimaryAccess().getAlternatives(), "rule__Primary__Alternatives");
					put(grammarAccess.getAtomicPredicateAccess().getAlternatives(), "rule__AtomicPredicate__Alternatives");
					put(grammarAccess.getOR_OPERATORAccess().getAlternatives(), "rule__OR_OPERATOR__Alternatives");
					put(grammarAccess.getAND_OPERATORAccess().getAlternatives(), "rule__AND_OPERATOR__Alternatives");
					put(grammarAccess.getNOT_OPERATORAccess().getAlternatives(), "rule__NOT_OPERATOR__Alternatives");
					put(grammarAccess.getBoolConstAccess().getAlternatives(), "rule__BoolConst__Alternatives");
					put(grammarAccess.getElementIDAccess().getAlternatives(), "rule__ElementID__Alternatives");
					put(grammarAccess.getRelationalOperatorsAccess().getAlternatives(), "rule__RelationalOperators__Alternatives");
					put(grammarAccess.getEqualityOperatorsAccess().getAlternatives(), "rule__EqualityOperators__Alternatives");
					put(grammarAccess.getPlusMinusOperatorsAccess().getAlternatives(), "rule__PlusMinusOperators__Alternatives");
					put(grammarAccess.getModMultDivOperatorsAccess().getAlternatives(), "rule__ModMultDivOperators__Alternatives");
					put(grammarAccess.getImpliesOperatorAccess().getAlternatives(), "rule__ImpliesOperator__Alternatives");
					put(grammarAccess.getCitModelAccess().getGroup(), "rule__CitModel__Group__0");
					put(grammarAccess.getCitModelAccess().getGroup_6(), "rule__CitModel__Group_6__0");
					put(grammarAccess.getParameterAccess().getGroup(), "rule__Parameter__Group__0");
					put(grammarAccess.getBoolAccess().getGroup(), "rule__Bool__Group__0");
					put(grammarAccess.getEnumerativeAccess().getGroup(), "rule__Enumerative__Group__0");
					put(grammarAccess.getEnumerativeAccess().getGroup_1(), "rule__Enumerative__Group_1__0");
					put(grammarAccess.getElementAccess().getGroup(), "rule__Element__Group__0");
					put(grammarAccess.getRangeAccess().getGroup(), "rule__Range__Group__0");
					put(grammarAccess.getRangeAccess().getGroup_7(), "rule__Range__Group_7__0");
					put(grammarAccess.getConstraintAccess().getGroup(), "rule__Constraint__Group__0");
					put(grammarAccess.getImpliesExpressionAccess().getGroup(), "rule__ImpliesExpression__Group__0");
					put(grammarAccess.getImpliesExpressionAccess().getGroup_1(), "rule__ImpliesExpression__Group_1__0");
					put(grammarAccess.getOrExpressionAccess().getGroup(), "rule__OrExpression__Group__0");
					put(grammarAccess.getOrExpressionAccess().getGroup_1(), "rule__OrExpression__Group_1__0");
					put(grammarAccess.getAndExpressionAccess().getGroup(), "rule__AndExpression__Group__0");
					put(grammarAccess.getAndExpressionAccess().getGroup_1(), "rule__AndExpression__Group_1__0");
					put(grammarAccess.getEqualExpressionAccess().getGroup(), "rule__EqualExpression__Group__0");
					put(grammarAccess.getEqualExpressionAccess().getGroup_1(), "rule__EqualExpression__Group_1__0");
					put(grammarAccess.getRelationalExpressionAccess().getGroup(), "rule__RelationalExpression__Group__0");
					put(grammarAccess.getRelationalExpressionAccess().getGroup_1(), "rule__RelationalExpression__Group_1__0");
					put(grammarAccess.getPlusMinusAccess().getGroup(), "rule__PlusMinus__Group__0");
					put(grammarAccess.getPlusMinusAccess().getGroup_1(), "rule__PlusMinus__Group_1__0");
					put(grammarAccess.getModMultDivAccess().getGroup(), "rule__ModMultDiv__Group__0");
					put(grammarAccess.getModMultDivAccess().getGroup_1(), "rule__ModMultDiv__Group_1__0");
					put(grammarAccess.getPrimaryAccess().getGroup_1(), "rule__Primary__Group_1__0");
					put(grammarAccess.getNotExpressionAccess().getGroup(), "rule__NotExpression__Group__0");
					put(grammarAccess.getElementIDAccess().getGroup_3(), "rule__ElementID__Group_3__0");
					put(grammarAccess.getPossiblySignedNumberAccess().getGroup(), "rule__PossiblySignedNumber__Group__0");
					put(grammarAccess.getCitModelAccess().getNameAssignment_2(), "rule__CitModel__NameAssignment_2");
					put(grammarAccess.getCitModelAccess().getParametersAssignment_5(), "rule__CitModel__ParametersAssignment_5");
					put(grammarAccess.getCitModelAccess().getConstraintsAssignment_6_2(), "rule__CitModel__ConstraintsAssignment_6_2");
					put(grammarAccess.getBoolAccess().getNameAssignment_0(), "rule__Bool__NameAssignment_0");
					put(grammarAccess.getEnumerativeAccess().getNameAssignment_0(), "rule__Enumerative__NameAssignment_0");
					put(grammarAccess.getEnumerativeAccess().getElementsAssignment_1_2(), "rule__Enumerative__ElementsAssignment_1_2");
					put(grammarAccess.getElementAccess().getNameAssignment_0(), "rule__Element__NameAssignment_0");
					put(grammarAccess.getRangeAccess().getNameAssignment_0(), "rule__Range__NameAssignment_0");
					put(grammarAccess.getRangeAccess().getBeginAssignment_3(), "rule__Range__BeginAssignment_3");
					put(grammarAccess.getRangeAccess().getEndAssignment_5(), "rule__Range__EndAssignment_5");
					put(grammarAccess.getRangeAccess().getStepAssignment_7_1(), "rule__Range__StepAssignment_7_1");
					put(grammarAccess.getImpliesExpressionAccess().getOpAssignment_1_1(), "rule__ImpliesExpression__OpAssignment_1_1");
					put(grammarAccess.getImpliesExpressionAccess().getRightAssignment_1_2(), "rule__ImpliesExpression__RightAssignment_1_2");
					put(grammarAccess.getOrExpressionAccess().getRightAssignment_1_2(), "rule__OrExpression__RightAssignment_1_2");
					put(grammarAccess.getAndExpressionAccess().getRightAssignment_1_2(), "rule__AndExpression__RightAssignment_1_2");
					put(grammarAccess.getEqualExpressionAccess().getOpAssignment_1_1(), "rule__EqualExpression__OpAssignment_1_1");
					put(grammarAccess.getEqualExpressionAccess().getRightAssignment_1_2(), "rule__EqualExpression__RightAssignment_1_2");
					put(grammarAccess.getRelationalExpressionAccess().getOpAssignment_1_1(), "rule__RelationalExpression__OpAssignment_1_1");
					put(grammarAccess.getRelationalExpressionAccess().getRightAssignment_1_2(), "rule__RelationalExpression__RightAssignment_1_2");
					put(grammarAccess.getPlusMinusAccess().getOpAssignment_1_1(), "rule__PlusMinus__OpAssignment_1_1");
					put(grammarAccess.getPlusMinusAccess().getRightAssignment_1_2(), "rule__PlusMinus__RightAssignment_1_2");
					put(grammarAccess.getModMultDivAccess().getOpAssignment_1_1(), "rule__ModMultDiv__OpAssignment_1_1");
					put(grammarAccess.getModMultDivAccess().getRightAssignment_1_2(), "rule__ModMultDiv__RightAssignment_1_2");
					put(grammarAccess.getAtomicPredicateAccess().getBoolConstAssignment_0(), "rule__AtomicPredicate__BoolConstAssignment_0");
					put(grammarAccess.getAtomicPredicateAccess().getNameAssignment_1(), "rule__AtomicPredicate__NameAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public CTWedgeGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CTWedgeGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
