/**
 * generated by Xtext 2.13.0
 */
package ctwedge.ctWedge.impl;

import ctwedge.ctWedge.Bool;
import ctwedge.ctWedge.CtWedgePackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Bool</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BoolImpl extends ParameterImpl implements Bool
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BoolImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CtWedgePackage.Literals.BOOL;
  }

} //BoolImpl
