/*
 * generated by Xtext 2.13.0
 */
package ctwedge.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link CTWedgeWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractCTWedgeWebModule extends DefaultWebModule {

}
