/*
 * generated by Xtext 2.12.0
 */
package ctwedge.ui.wizard;

import org.eclipse.ui.dialogs.WizardNewProjectCreationPage;

public class CTWedgeWizardNewProjectCreationPage extends WizardNewProjectCreationPage {

	public CTWedgeWizardNewProjectCreationPage(String pageName) {
		super(pageName);
	}

}
