/*
 * generated by Xtext 2.15.0
 */
package ctwedge.tests

import com.google.inject.Inject
import ctwedge.ctWedge.CitModel
import ctwedge.ctWedge.Enumerative
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Test
import org.junit.runner.RunWith
import org.junit.Assert

@RunWith(XtextRunner)
@InjectWith(CTWedgeInjectorProvider)
class CTWedgeParsingTest {
	@Inject
	ParseHelper<CitModel> parseHelper

	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			/*
									 * This is an example model
									 */
									Model Phone
									 Parameters:
									   emailViewer : Boolean
									   textLines:  [ 25 .. 30 ]
									   display : {16MC, 8MC, BW}
									
									 Constraints:
									   # emailViewer => textLines > 28 #
		''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''',errors.isEmpty)
	}

	@Test
	def void EnumComma() {
		var result = parseHelper.parse('''Model Phone Parameters:  display : {16MC, 8MC, BW}''')
		Assert.assertNotNull(result)
		var errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.empty)
		Assert.assertEquals(3, (result.parameters.get(0) as Enumerative).elements.size);
		// with spaces
		result = parseHelper.parse('''Model Phone Parameters:  display : {16MC 8MC BW}''')
		Assert.assertNotNull(result)
		errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''',errors.empty)
		Assert.assertEquals(3, (result.parameters.get(0) as Enumerative).elements.size);
		// with spaces and commas mixed
		result = parseHelper.parse('''Model Phone Parameters:  display : {16MC, 8MC BW}''')
		Assert.assertNotNull(result)
		errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''',errors.empty)
		Assert.assertEquals(3, (result.parameters.get(0) as Enumerative).elements.size);
		// some errors
		result = parseHelper.parse('''Model Phone Parameters:  display : {16MC, , 8MC BW}''')
		Assert.assertNotNull(result)
		errors = result.eResource.errors
		Assert.assertFalse(errors.isEmpty)
		println(errors.join(", "));
		
	}

	@Test
	def void EnumWithEmpty() {
		var result = parseHelper.parse('''Model Phone Parameters:  display : {16MC, 8MC, BW, }''')
		Assert.assertNotNull(result)
		var errors = result.eResource.errors
		Assert.assertFalse(errors.isEmpty)
	}

	@Test
	def void EnumWithBoolean() {
		var result = parseHelper.parse('''Model Phone Parameters:  display : {TRUE, FALSE}''')
		Assert.assertNotNull(result)
		var errors = result.eResource.errors
		Assert.assertFalse(errors.isEmpty)
		println(result.parameters.get(0))
		Assert.assertEquals(3, (result.parameters.get(0) as Enumerative).elements.size);
	}


	@Test
	def void loadModelBoolean() {
		loadModelBooleanConstraint("A = B")
		loadModelBooleanConstraint("A == B")
		loadModelBooleanConstraint("A <=> B")
		loadModelBooleanConstraint("A = TRUE")
		loadModelBooleanConstraint("A=TRUE")
	}

	def void loadModelBooleanConstraint(String s){
		val result = parseHelper.parse('''
		/*
								 * This is an example model
								 */
								Model Phone
								 Parameters:
								   A : Boolean
								   B : Boolean
								
								 Constraints:
								   # ''' + s + ''' #
		''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''',errors.isEmpty)
		val model = result as CitModel
		Assert.assertNotNull(model)
		Assert.assertEquals(1, model.constraints.size)
		
	}

}
