/**
 * generated by Xtext 2.15.0
 */
package ctwedge.tests;

import com.google.inject.Inject;
import ctwedge.ctWedge.CitModel;
import ctwedge.tests.CTWedgeInjectorProvider;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(CTWedgeInjectorProvider.class)
@SuppressWarnings("all")
public class CTWedgeParsingTest {
  @Inject
  private ParseHelper<CitModel> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("/*");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t ");
      _builder.append("* This is an example model");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t ");
      _builder.append("*/");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t");
      _builder.append("Model Phone");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t ");
      _builder.append("Parameters:");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t   ");
      _builder.append("emailViewer : Boolean");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t   ");
      _builder.append("textLines:  [ 25 .. 30 ]");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t   ");
      _builder.append("display : {16MC, 8MC, BW}");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t ");
      _builder.append("Constraints:");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t   ");
      _builder.append("# emailViewer => textLines > 28 #");
      _builder.newLine();
      final CitModel result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_1.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_1.toString());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
