/*
 * generated by Xtext 2.34.0
 */
package ctwedge;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CTWedgeStandaloneSetup extends CTWedgeStandaloneSetupGenerated {

	public static void doSetup() {
		new CTWedgeStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
