/*
 * generated by Xtext 2.14.0
 */
package ctwedge.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCTWedgeScopeProvider extends DelegatingScopeProvider {
}
