/*
 * generated by Xtext 2.14.0
 */
package ctwedge.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractCTWedgeValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(ctwedge.ctWedge.CtWedgePackage.eINSTANCE);
		return result;
	}
}
