/*
 * generated by Xtext 2.22.0
 */
package ctwedge.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CTWedgeUiModule extends AbstractCTWedgeUiModule {

	public CTWedgeUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
