/*
 * generated by Xtext 2.12.0
 */
package ctwedge.ui;

import com.google.inject.Injector;
import ctwedge.ui.internal.CtwedgeActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CTWedgeExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return CtwedgeActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return CtwedgeActivator.getInstance().getInjector(CtwedgeActivator.CTWEDGE_CTWEDGE);
	}
	
}
