/*
 * generated by Xtext 2.13.0
 */
package ctwedge.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class CTWedgeWebModule extends AbstractCTWedgeWebModule {
}
