/*
 * generated by Xtext 2.34.0
 */
package ctwedge.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class CTWedgeWebModule extends AbstractCTWedgeWebModule {
}
